### ISSUE TITLE
View call to get_total_supply fails

### ISSUE THREAD

**Issue by ilblackdragon** [near-examples/rust-fungible-token#4]
A developer received next error after deploying and calling view function `get_total_supply`:

```
get_total_supply failed: wasm execution failed with error: FunctionCallError(HostError(ProhibitedInView { method_name: "attached_deposit" })).
{
  "error": "wasm execution failed with error: FunctionCallError(HostError(ProhibitedInView { method_name: \"attached_deposit\" }))",
  "logs": [],
  "block_height": 6205,
  "block_hash": "9VogQMVyuhGRDtxPuTgh6hwcEc29VdnaZnRkpKcErA49"
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:35:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:166:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-shell/index.js:44:33)
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9)
```

**Comment by mikedotexe** [comment]
Strange, I wasn't able to reproduce this on `master` this morning.

<img width="1160" alt="Screenshot 2020-04-13 08 03 52" src="https://user-images.githubusercontent.com/1042667/79132067-7dd91d00-7d5e-11ea-8ada-4b9471e0f119.png">

**Comment by evgenykuzyakov** [comment]
It might be related to `#[payable]` that Alexey added to `near-sdk-rs`. Seems we need to remove it from view methods, but we don't distinguish view methods.

**Comment by evgenykuzyakov** [comment]
https://github.com/near/near-sdk-rs/issues/134

**Comment by evgenykuzyakov** [comment]
This should be fixed in `near-sdk = "0.9.1"`
